"""add_max_grade_to_labs

Revision ID: fae5e62d371f
Revises: 006_add_role_indexes
Create Date: 2025-12-22 16:24:32.263322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fae5e62d371f'
down_revision: Union[str, None] = '006_add_role_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attendance_group_date', table_name='attendance')
    op.drop_table('attendance')
    op.add_column('labs', sa.Column('max_grade', sa.Integer(), nullable=False))
    op.add_column('lecture_groups', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_lecture_group', 'lecture_groups', ['lecture_id', 'group_id'])
    op.drop_column('lecture_groups', 'available_from')
    op.drop_index('ix_lectures_is_published', table_name='lectures')
    op.drop_index('ix_users_group_role', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_group_role', 'users', ['group_id', 'role'], unique=False)
    op.create_index('ix_lectures_is_published', 'lectures', ['is_published'], unique=False)
    op.add_column('lecture_groups', sa.Column('available_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_lecture_group', 'lecture_groups', type_='unique')
    op.drop_column('lecture_groups', 'updated_at')
    op.drop_column('labs', 'max_grade')
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendance_status_enum'), server_default=sa.text("'ABSENT'::attendance_status_enum"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='attendance_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='attendance_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='attendance_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='attendance_pkey'),
    sa.UniqueConstraint('student_id', 'date', name='uq_attendance_student_date')
    )
    op.create_index('idx_attendance_group_date', 'attendance', ['group_id', 'date'], unique=False)
    # ### end Alembic commands ###