"""add_last_run_at_to_schedule_parser_config

Revision ID: 0af381a0f3bd
Revises: 046
Create Date: 2026-01-07 20:40:17.295045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0af381a0f3bd'
down_revision: Union[str, None] = '046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'attestation_type',
               existing_type=postgresql.ENUM('FIRST', 'SECOND', name='attestationtype'),
               type_=sa.Enum('FIRST', 'SECOND', name='attestationtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('attendance', 'status',
               existing_type=postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendance_status_enum'),
               type_=sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendance_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ABSENT'::attendance_status_enum"))
    op.alter_column('attendance', 'lesson_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LECTURE', 'PRACTICE', 'LAB', name='attendancelessontype', native_enum=False),
               existing_nullable=True)
    op.alter_column('attestation_settings', 'attestation_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('FIRST', 'SECOND', name='attestationtype', native_enum=False),
               existing_nullable=False)
    op.drop_constraint('group_reports_code_key', 'group_reports', type_='unique')
    op.drop_index('idx_group_reports_code', table_name='group_reports')
    op.create_index(op.f('ix_group_reports_code'), 'group_reports', ['code'], unique=True)
    op.create_index(op.f('ix_group_reports_created_by'), 'group_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_group_reports_group_id'), 'group_reports', ['group_id'], unique=False)
    op.alter_column('groups', 'grading_scale',
               existing_type=postgresql.ENUM('FIVE', 'TEN', 'HUNDRED', name='gradingscale'),
               type_=sa.Enum('FIVE', 'TEN', 'HUNDRED', name='gradingscale', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'TEN'::gradingscale"))
    op.alter_column('lab_settings', 'grading_scale',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('FIVE', 'TEN', 'HUNDRED', name='gradingscale', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'10'::character varying"))
    op.alter_column('labs', 'theory_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Теоретическая часть (Lexical JSON)',
               existing_nullable=True)
    op.alter_column('labs', 'practice_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Общее задание практики (Lexical JSON)',
               existing_nullable=True)
    op.alter_column('labs', 'variants',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Массив вариантов [{number, description, test_data}, ...]',
               existing_nullable=True)
    op.alter_column('labs', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Список контрольных вопросов',
               existing_nullable=True)
    op.alter_column('labs', 'is_sequential',
               existing_type=sa.BOOLEAN(),
               comment='Требуется ли сдача предыдущей лабы для доступа',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('labs', 'public_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_labs_deleted_at', table_name='labs', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('lecture_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_lecture_images_lecture_id', table_name='lecture_images')
    op.create_index(op.f('ix_lecture_images_lecture_id'), 'lecture_images', ['lecture_id'], unique=False)
    op.add_column('lectures', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_lectures_deleted_at', 'lectures', ['deleted_at'], unique=False)
    op.alter_column('lesson_grades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lesson_grades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_lesson_grades_lesson_student', 'lesson_grades', ['lesson_id', 'student_id'], unique=False)
    op.create_index('idx_lesson_grades_work_number', 'lesson_grades', ['work_number'], unique=False)
    op.alter_column('lessons', 'lesson_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LECTURE', 'PRACTICE', 'LAB', name='lessontype', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_lessons_group_id'), 'lessons', ['group_id'], unique=False)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_report_views_report_id'), 'report_views', ['report_id'], unique=False)
    op.drop_index('idx_schedule_conflicts_lesson', table_name='schedule_conflicts')
    op.drop_index('idx_schedule_conflicts_resolved', table_name='schedule_conflicts')
    op.alter_column('schedule_items', 'day_of_week',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='dayofweek', native_enum=False),
               existing_nullable=False)
    op.alter_column('schedule_items', 'lesson_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LECTURE', 'PRACTICE', 'LAB', name='lessontype', native_enum=False),
               existing_nullable=False)
    op.alter_column('schedule_items', 'week_parity',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('ODD', 'EVEN', name='weekparity', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_schedule_items_group_id'), 'schedule_items', ['group_id'], unique=False)
    op.add_column('schedule_parser_configs', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    op.alter_column('student_transfers', 'attestation_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('FIRST', 'SECOND', name='attestationtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('student_transfers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_transfers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_student_transfers_transfer_date', table_name='student_transfers')
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'ready_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Когда студент нажал 'Готов сдать'",
               existing_nullable=True)
    op.alter_column('submissions', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда преподаватель принял работу',
               existing_nullable=True)
    op.alter_column('submissions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Когда сдача была удалена (soft-delete)',
               existing_nullable=True)
    op.drop_index('idx_submissions_deleted_at', table_name='submissions', postgresql_where='(deleted_at IS NULL)')
    op.alter_column('teacher_subject_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teacher_subject_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_tsa_group_id', table_name='teacher_subject_assignments')
    op.drop_index('ix_tsa_subject_id', table_name='teacher_subject_assignments')
    op.drop_index('ix_tsa_teacher_id', table_name='teacher_subject_assignments')
    op.create_index(op.f('ix_teacher_subject_assignments_group_id'), 'teacher_subject_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_subject_id'), 'teacher_subject_assignments', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_assignments_teacher_id'), 'teacher_subject_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_subject_assignments_teacher_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_subject_id'), table_name='teacher_subject_assignments')
    op.drop_index(op.f('ix_teacher_subject_assignments_group_id'), table_name='teacher_subject_assignments')
    op.create_index('ix_tsa_teacher_id', 'teacher_subject_assignments', ['teacher_id'], unique=False)
    op.create_index('ix_tsa_subject_id', 'teacher_subject_assignments', ['subject_id'], unique=False)
    op.create_index('ix_tsa_group_id', 'teacher_subject_assignments', ['group_id'], unique=False)
    op.alter_column('teacher_subject_assignments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teacher_subject_assignments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_submissions_deleted_at', 'submissions', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('submissions', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда сдача была удалена (soft-delete)',
               existing_nullable=True)
    op.alter_column('submissions', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Когда преподаватель принял работу',
               existing_nullable=True)
    op.alter_column('submissions', 'ready_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Когда студент нажал 'Готов сдать'",
               existing_nullable=True)
    op.alter_column('subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_student_transfers_transfer_date', 'student_transfers', ['transfer_date'], unique=False)
    op.alter_column('student_transfers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_transfers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('student_transfers', 'attestation_type',
               existing_type=sa.Enum('FIRST', 'SECOND', name='attestationtype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('schedule_parser_configs', 'last_run_at')
    op.drop_index(op.f('ix_schedule_items_group_id'), table_name='schedule_items')
    op.alter_column('schedule_items', 'week_parity',
               existing_type=sa.Enum('ODD', 'EVEN', name='weekparity', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('schedule_items', 'lesson_type',
               existing_type=sa.Enum('LECTURE', 'PRACTICE', 'LAB', name='lessontype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('schedule_items', 'day_of_week',
               existing_type=sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='dayofweek', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index('idx_schedule_conflicts_resolved', 'schedule_conflicts', ['resolved'], unique=False)
    op.create_index('idx_schedule_conflicts_lesson', 'schedule_conflicts', ['lesson_id'], unique=False)
    op.drop_index(op.f('ix_report_views_report_id'), table_name='report_views')
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_lessons_group_id'), table_name='lessons')
    op.alter_column('lessons', 'lesson_type',
               existing_type=sa.Enum('LECTURE', 'PRACTICE', 'LAB', name='lessontype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index('idx_lesson_grades_work_number', table_name='lesson_grades')
    op.drop_index('idx_lesson_grades_lesson_student', table_name='lesson_grades')
    op.alter_column('lesson_grades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lesson_grades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_lectures_deleted_at', table_name='lectures')
    op.drop_column('lectures', 'deleted_at')
    op.drop_index(op.f('ix_lecture_images_lecture_id'), table_name='lecture_images')
    op.create_index('idx_lecture_images_lecture_id', 'lecture_images', ['lecture_id'], unique=False)
    op.alter_column('lecture_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_labs_deleted_at', 'labs', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('labs', 'public_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('labs', 'is_sequential',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Требуется ли сдача предыдущей лабы для доступа',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('labs', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Список контрольных вопросов',
               existing_nullable=True)
    op.alter_column('labs', 'variants',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Массив вариантов [{number, description, test_data}, ...]',
               existing_nullable=True)
    op.alter_column('labs', 'practice_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Общее задание практики (Lexical JSON)',
               existing_nullable=True)
    op.alter_column('labs', 'theory_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Теоретическая часть (Lexical JSON)',
               existing_nullable=True)
    op.alter_column('lab_settings', 'grading_scale',
               existing_type=sa.Enum('FIVE', 'TEN', 'HUNDRED', name='gradingscale', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'10'::character varying"))
    op.alter_column('groups', 'grading_scale',
               existing_type=sa.Enum('FIVE', 'TEN', 'HUNDRED', name='gradingscale', native_enum=False),
               type_=postgresql.ENUM('FIVE', 'TEN', 'HUNDRED', name='gradingscale'),
               existing_nullable=True,
               existing_server_default=sa.text("'TEN'::gradingscale"))
    op.drop_index(op.f('ix_group_reports_group_id'), table_name='group_reports')
    op.drop_index(op.f('ix_group_reports_created_by'), table_name='group_reports')
    op.drop_index(op.f('ix_group_reports_code'), table_name='group_reports')
    op.create_index('idx_group_reports_code', 'group_reports', ['code'], unique=True)
    op.create_unique_constraint('group_reports_code_key', 'group_reports', ['code'])
    op.alter_column('attestation_settings', 'attestation_type',
               existing_type=sa.Enum('FIRST', 'SECOND', name='attestationtype', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('attendance', 'lesson_type',
               existing_type=sa.Enum('LECTURE', 'PRACTICE', 'LAB', name='attendancelessontype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('attendance', 'status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendance_status_enum', native_enum=False),
               type_=postgresql.ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendance_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'ABSENT'::attendance_status_enum"))
    op.alter_column('activities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('activities', 'attestation_type',
               existing_type=sa.Enum('FIRST', 'SECOND', name='attestationtype', native_enum=False),
               type_=postgresql.ENUM('FIRST', 'SECOND', name='attestationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###