"""add_constraints_and_indexes

Revision ID: 44dd67787045
Revises: 0af381a0f3bd
Create Date: 2026-01-07 20:46:16.556695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44dd67787045'
down_revision: Union[str, None] = '0af381a0f3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_lessons_date', 'lessons', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lessons_date', table_name='lessons')
    # ### end Alembic commands ###