from .activity import ActivityCreate, ActivityResponse, ActivityUpdate
from .admin import DeleteResponse, StatsResponse
from .attendance import (
    AttendanceCreate,
    AttendanceResponse,
    AttendanceStatsResponse,
    AttendanceStatusSchema,
    AttendanceUpdate,
    BulkAttendanceCreate,
    BulkAttendanceItem,
    BulkAttendanceResponse,
)
from .attestation import (
    AttestationResult,
    AttestationResultResponse,
    AttestationSettingsBase,
    AttestationSettingsCreate,
    AttestationSettingsResponse,
    AttestationSettingsUpdate,
    AttestationType,
    ComponentBreakdown,
    GroupAttestationResponse,
)
from .group import (
    AssignSubgroupRequest,
    AssignSubgroupResponse,
    ClearSubgroupsResponse,
    GroupCreate,
    GroupDetailResponse,
    GroupResponse,
    StudentImport,
    StudentInGroupResponse,
    StudentUpdate,
)
from .lab_settings import GradingScale, LabSettingsResponse, LabSettingsUpdate
from .lecture import (
    LectureCreate,
    LectureImageResponse,
    LectureListResponse,
    LectureResponse,
    LectureUpdate,
    PublicLinkResponse,
)
from .report import (
    ActivityRecord,
    AttendanceDistribution,
    AttendanceRecord,
    ExportResponse,
    LabProgress,
    LabSubmission,
    PinVerifyRequest,
    PinVerifyResponse,
    PublicReportData,
    PublicStudentData,
    ReportCreate,
    ReportListResponse,
    ReportResponse,
    ReportType,
    ReportUpdate,
    ReportViewRecord,
    ReportViewsResponse,
    ReportViewStats,
    StudentDetailData,
)
from .schedule import (
    GenerateLessonsRequest,
    GenerateLessonsResponse,
    LessonCreate,
    LessonResponse,
    LessonUpdate,
    ScheduleItemCreate,
    ScheduleItemResponse,
    ScheduleItemUpdate,
)
from .student import StudentLabSubmission, StudentProfileOut, StudentStats
from .user import (
    StudentInGroup,
    TeacherContacts,
    TeacherContactsResponse,
    TeacherContactsUpdate,
    UserCreate,
    UserResponse,
    UserUpdate,
)

__all__ = [
    "UserCreate",
    "UserResponse",
    "StudentInGroup",
    "UserUpdate",
    "TeacherContactsUpdate",
    "TeacherContactsResponse",
    "TeacherContacts",
    "GroupCreate",
    "GroupResponse",
    "StudentImport",
    "GroupDetailResponse",
    "StudentInGroupResponse",
    "StudentUpdate",
    "AssignSubgroupRequest",
    "AssignSubgroupResponse",
    "ClearSubgroupsResponse",
    "LabSettingsResponse",
    "LabSettingsUpdate",
    "GradingScale",
    # Attestation schemas
    "AttestationType",
    "AttestationSettingsBase",
    "AttestationSettingsCreate",
    "AttestationSettingsUpdate",
    "AttestationSettingsResponse",
    "ComponentBreakdown",
    "AttestationResult",
    "AttestationResultResponse",
    "GroupAttestationResponse",
    # Attendance schemas
    "AttendanceStatusSchema",
    "AttendanceCreate",
    "AttendanceUpdate",
    "AttendanceResponse",
    "BulkAttendanceItem",
    "BulkAttendanceCreate",
    "BulkAttendanceResponse",
    "AttendanceStatsResponse",
    # Student schemas
    "StudentLabSubmission",
    "StudentStats",
    "StudentProfileOut",
    "StatsResponse",
    "DeleteResponse",
    # Activity schemas
    "ActivityCreate",
    "ActivityUpdate",
    "ActivityResponse",
    # Schedule schemas
    "ScheduleItemCreate",
    "ScheduleItemUpdate",
    "ScheduleItemResponse",
    "LessonCreate",
    "LessonUpdate",
    "LessonResponse",
    "GenerateLessonsRequest",
    "GenerateLessonsResponse",
    # Lecture schemas
    "LectureCreate",
    "LectureUpdate",
    "LectureResponse",
    "LectureListResponse",
    "LectureImageResponse",
    "PublicLinkResponse",
    # Report schemas
    "ReportType",
    "ReportCreate",
    "ReportUpdate",
    "ReportResponse",
    "ReportListResponse",
    "PublicReportData",
    "PublicStudentData",
    "StudentDetailData",
    "AttendanceDistribution",
    "LabProgress",
    "AttendanceRecord",
    "LabSubmission",
    "ActivityRecord",
    "PinVerifyRequest",
    "PinVerifyResponse",
    "ExportResponse",
    "ReportViewStats",
    "ReportViewRecord",
    "ReportViewsResponse",
]
